name: Run scrappers

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Build
        run: go build -v

      - name: Run startup-sensei
        run: ./startup-sensei

      - uses: actions4git/add-commit-push@v1
